services:
  reality-bot:
    container_name: reality-bot
    build:
      context: .
      args:
        - DB_URI=${DB_URI}
        - MAIL_SMTP_LOGIN=${MAIL_SMTP_LOGIN}
        - MAIL_SMTP_PASSWORD=${MAIL_SMTP_PASSWORD}
        - MAIL_SMTP_SERVER=${MAIL_SMTP_SERVER}
        - MAIL_SMTP_PORT=${MAIL_SMTP_PORT}
        - MAIL_FROM_EMAIL=${MAIL_FROM_EMAIL}
    image: reality-bot:latest
    environment:
      DB_URI: ${DB_URI}
      MAIL_SMTP_LOGIN: ${MAIL_SMTP_LOGIN}
      MAIL_SMTP_PASSWORD: ${MAIL_SMTP_PASSWORD}
      MAIL_SMTP_SERVER: ${MAIL_SMTP_SERVER}
      MAIL_SMTP_PORT: ${MAIL_SMTP_PORT}
      MAIL_FROM_EMAIL: ${MAIL_FROM_EMAIL}
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - nginx-proxy-manager_default

networks:
  nginx-proxy-manager_default:
    driver: bridge
